artifacts_root: artifacts
# when exectuting pipeline so it create one folder called artifacts
#inside artifacts it save all the artifacts related data ingestion
#data validation, data tranformatin, model training, model evaluation


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://github.com/talhanaseem08/data-for-projects/raw/refs/heads/main/winequality-red.zip"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion